### ISSUE TITLE
Message d'erreur lors d'une erreur de login

### ISSUE THREAD

**Issue by san41** [NextDom/plugin-Meross#11]
## Description

Lors de la configuration du plugin, j'avais fait une erreur sur mon identifiant, sauf que lors de la tentative de récupération, je n'avais pas de massage pour préciser mon erreur d'identifiant. En faite je n'avais rien, même dans les logs, je n'avais pas un message assez clair pour comprendre mon erreur. (Merci discord) 

## Etapes à reproduire (pour les bugs)

1. Installer le plugin
2. Configurer avec un mauvais ID
3. Tenter de récupérer les équipements

## Contexte:

Log (Http.error) 
Traceback (most recent call last):
  File "/var/www/html/plugins/meross/3rdparty/meross.py", line 370, in <module>
    d_devices = ConnectAndRefreshAll(email, password)
  File "/var/www/html/plugins/meross/3rdparty/meross.py", line 185, in ConnectAndRefreshAll
    devices = httpHandler.list_supported_devices()
  File "/var/www/html/plugins/meross/3rdparty/meross_iot/meross_iot/api.py", line 120, in list_supported_devices
    for dev in self.list_devices():
  File "/var/www/html/plugins/meross/3rdparty/meross_iot/meross_iot/api.py", line 114, in list_devices
    raise UnauthorizedException()
meross_iot.api.UnauthorizedException
/var/www/html/plugins/meross/core/class/../../3rdparty/meross.sh: 22: /var/www/html/plugins/meross/core/class/../../3rdparty/meross.sh: [[: not found

(équivalent au logs que j'avais sur jeedom)

## Proposition de solution (optionnel):

- Localiser le problème ou faire afficher un message d'erreur pour identifiant erroné et faire une vérification des id lors de la sauvegarde de la configuration

## Environnement:

* **Version (Jeedom)**: 3.3.24 (un passage sous nextdom est bientôt programmé)
* **Plateforme**: Debian 9 
* **Version du Plugin**: 3323d56 ( dernière version du master depuis le 19 fév?)

**Comment by Astral0** [comment]
C'est clairement un pb de login/password : la partie Python du module a remonté une exception 👍  meross_iot.api.UnauthorizedException

Il faut qu'on gère cette exception et qu'on la remonte au niveau du script bash meross.sh.

**Comment by Astral0** [comment]
Est-ce que tu peux ressayer avec la version publiée ce soir ?
