### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PROTOCOL_TLS'

### ISSUE THREAD

**Issue by b-benj** [NextDom/plugin-Meross#13]
Bonjour,

Merci pour ce plugin ! Voici mon problème.

## Description:

Impossible de voir mes prises au sein de jeedom. Je suis donc aller exécuter la commande (sans me tromper de user/mdp) permettant de récupérer les devices et j'ai eu cette erreur : AttributeError: 'module' object has no attribute 'PROTOCOL_TLS'.

La trace complète si ça peut aider : 
Traceback (most recent call last):
  File "/var/www/html/plugins/meross/3rdparty/meross.py", line 370, in <module>
    d_devices = ConnectAndRefreshAll(email, password)
  File "/var/www/html/plugins/meross/3rdparty/meross.py", line 185, in ConnectAndRefreshAll
    devices = httpHandler.list_supported_devices()
  File "/var/www/html/plugins/meross/3rdparty/meross_iot/meross_iot/api.py", line 122, in list_supported_devices
    device = build_wrapper(self._token, self._key, self._userid, deviceType, dev)
  File "/var/www/html/plugins/meross/3rdparty/meross_iot/meross_iot/device_factory.py", line 11, in build_wrapper
    return Mss310(token, key, user_id,**device_specs)
File "/var/www/html/plugins/meross/3rdparty/meross_iot/meross_iot/supported_devices/power_plugs.py", line 129, in init
    tls_version=ssl.PROTOCOL_TLS,
AttributeError: 'module' object has no attribute 'PROTOCOL_TLS'
/var/www/html/plugins/meross/core/class/../../3rdparty/meross.sh: 22: /var/www/html/plugins/meross/core/class/../../3rdparty/meross.sh: [[: not found

## Contexte:

Mon Jeedom est déployer sur mon synology dans un conteneur docker.

## Proposition de solution (optionnel):
Après quelques recherches je suis tombé là dessus mais je bloque.
https://github.com/fastly/fastly-py/pull/35

## Environnement:
* **Version du Plugin**: master

**Comment by b-benj** [comment]
Problème résolu dans le pull request, ou sur ma branche perso : https://github.com/b-benj/plugin-Meross/tree/feature/improve-request-TLS
