### ISSUE TITLE
Pb de synchro ?

### ISSUE THREAD

**Issue by Lucmonin** [NextDom/plugin-Meross#15]
Bonjour,

Je me demande si la sychro fonctionne actuellement. Les essais que j'ai fait ainsi que les logs me laissent penser que le plugin ne parvient pas à faire la syncro avec le cloud Meross. 
Cela fonctionne-til chez vous? Y a-t-il eu des changements sur le cloud Meross?

## Etapes à reproduire (pour les bugs)
[2019-08-08 20:34:39][DEBUG] : syncMeross: Load devices from Meross Cloud
[2019-08-08 20:34:39][DEBUG] : shell_exec: sh /usr/share/nginx/www/jeedom/plugins/meross/core/class/../../3rdparty/meross.sh --email xxx --password xxx --refresh --show
[2019-08-08 20:34:39][DEBUG] : shell_exec: result:
[2019-08-08 20:34:39][DEBUG] : syncMeross: synchronization completed.
[2019-08-08 20:45:10][DEBUG] : cron15: Update informations for all eqLogics...
[2019-08-08 20:45:10][DEBUG] : syncMeross: Load devices from Meross Cloud
[2019-08-08 20:45:10][DEBUG] : shell_exec: sh /usr/share/nginx/www/jeedom/plugins/meross/core/class/../../3rdparty/meross.sh --email xxx --password xxx --refresh --show
[2019-08-08 20:45:10][DEBUG] : shell_exec: result:
[2019-08-08 20:45:10][DEBUG] : syncMeross: synchronization completed.
[2019-08-08 20:45:10][DEBUG] : cron15: Cron completed.

Sauf qu'entre temps j'ai modifié le mot de passe pour faire un test et que cela n'a même pas fait sourciller le script.

Merci de vos idées/suggestions? !

Je suis sous Jeedom V3.3.29 et j'ai installé le plugin il y a deux jours (65d638791fbe9a3439de09fc078373cfc1e34264)

**Comment by Astral0** [comment]
Tu pourrais lancer à la main le script qui est derrière shell_exec ? Normalement ça envoie le résultat dans la sortie standard.
Désolé je ne peux pas tester je suis en congés..

**Comment by b-benj** [comment]
Personnellement, ça fonctionne toujours chez moi. Pas de changement côté Meross du coup.

**Comment by Lucmonin** [comment]
Bonjour,

Désolé de te déranger pendant tes vacances, d'autant que je pense que le problème ne vient probablement pas du plugin ni du cloud Meross (aux vues de la réponse de b-benj <https://github.com/b-benj>), mais plutôt de mon incompétence.
Donc, si j'ai bien compris ce que tu me demandais, j'ai mis :
sh /usr/share/nginx/www/jeedom/plugins/meross/core/class/../../3rdparty/meross.sh --email xxx --password xxx --refresh --show dans un terminal en ssh
et cela m'a répondu :
timeout: failed to run command ‘python3’: No such file or directory
/usr/share/nginx/www/jeedom/plugins/meross/core/class/../../3rdparty/meross.sh: 22: /usr/share/nginx/www/jeedom/plugins/meross/core/class/../../3rdparty/meross.sh: [[: not found

Si une réponse te semble évidente, je veux bien que tu me la dises, sinon laisse tomber car je crois que je me suis un peu aventuré dans la "cour des grands" ...
Merci en tous cas et bonnes vacances, 
Luc


8 août 2019 à 22:02 de notifications@github.com:

**Comment by b-benj** [comment]
D'après ton message d'erreur, python3 n'est pas installé. Je ne sais pas sur quel environnement tourne ton jeedom, mais il faut pour moi installer python3.

**Comment by Lucmonin** [comment]
Bonjour,

Merci de ton aide, j'étais persuadé que Python était installé nativement sous Debian (je suis sous 8.11). Une fois installé, cela marche parfaitement.
Merci encore,
Luc

20 août 2019 à 14:58 de notifications@github.com:

**Comment by byackee** [comment]
@Lucmonin  ton on est règle? On va ajouter l installation de python3 si non présent

**Comment by Lucmonin** [comment]
Bonjour,

Oui, merci, mon problème a été réglé, dès que B-benj m'a aidé à comprendre qu'il me manquait Python3 (comme je l'ai écrit, je pensais qu'il était installé nativement sous Debian). 
Si vous avez la possibilité de lancer l'install de Python 3 automatiquement, je pense que ce serait effectivement une excellente chose car cela rendrait le plugin accessible aux plus novices (comme moi).
Merci à tous pour votre travail !


23 oct. 2019 à 07:55 de notifications@github.com:

**Comment by Lucmonin** [comment]
Bonjour,

Je réouvre le sujet car j'ai à nouveau les mêmes problèmes que la dernière fois depuis que j'ai effectué la mise à jour du plugin (janvier 2020) : plus  de synchro alors que tout fonctionnait parfaitement depuis des mois.
Cette fois ci, cela ne semble pas être un problème de lié à Python puisque j'ai mis à jour vers la dernière version (3.8.1).
Lorsque je lance la ligne de commande en manuel, cela me retourne :

Traceback (most recent call last):
  File "/usr/share/nginx/www/jeedom/plugins/meross/3rdparty/meross.py", line 11, in <module>
    from meross_iot.cloud.devices.subdevices.thermostats import ValveSubDevice, ThermostatV3Mode
  File "/usr/share/nginx/www/jeedom/plugins/meross/3rdparty/meross_iot/meross_iot/cloud/devices/subdevices/thermostats.py", line 2, in <module>
    from typing import Union
ImportError: No module named 'typing'

Je précise que je n'ai pas de Thermostat dans mes modules, juste des prises...

Merci d'avance pour vos conseils

**Comment by Astral0** [comment]
Je pense au contraire que c'est lié à Python.
Essaye de faire dans un terminal bash : 
`python3 -c 'import typing'
`

**Comment by Lucmonin** [comment]
Bonjour,

Merci de ta réactivité. La commande que tu cites m'indique :

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'typing'

**Comment by Astral0** [comment]
Je crois que tu es tombé dans ce problème : 
https://github.com/PyCQA/pydocstyle/issues/378

Ca a l'air lié à la version de Python. As tu la possibilité de la mettre à jour ou au contraire downgrader?

**Comment by Lucmonin** [comment]
Bonjour,

Merci beaucoup de ta réponse. Je pense que tu as certainement raison mais je viens de galérer pendant plusieurs heures pour upgrader python, mais sans succès.
J'ai essayé d'installer Python 3.8.1 en suivant cette procédure (https://linux.lyes-touati.com/installation-python-3-8), apparemment avec succès ( python3.8 -V donne Python 3.8.1)

sauf qu'en tapant 
python --versionje reste en version 2.7.9
J'ai donc essayer de passer par l’installation de pip, mais je me suis perdu en route :
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Je n'ai pas perdu mon temps car j'en ai compris davantage sur le fonctionnement de Python, mais globalement, je suis bloqué. La solution pourrait être de passer sous Stretch, je vais y réfléchir.

Je suis évidemment preneur de toute manip à réaliser. Sinon, peut être puis-je réinstaller l'ancienne version du plugin qui fonctionnait parfaitement chez moi, mais je n'ai pas trouvé comment faire depuis l'alternative market?

Merci en tous cas,

Luc



1 févr. 2020 à 11:25 de notifications@github.com:
