### ISSUE TITLE
Pb dans l'utilisation du plugin quand le mot de passe avec caractères spéciaux 

### ISSUE THREAD

**Issue by mnpg** [NextDom/plugin-Meross#19]
Pb dans l'utilisation du plugin - mot de passe avec caractères spéciaux 

## Etapes à reproduire (pour les bugs)

1. Utiliser un compte meross dont le mot de passe contient des caractères spéciaux
2. Aucune synchronisation n'est possible

Traceback (most recent call last):
  File "/var/www/html/plugins/meross/3rdparty/meross.py", line 370, in <module>
    d_devices = ConnectAndRefreshAll(email, password)
  File "/var/www/html/plugins/meross/3rdparty/meross.py", line 185, in ConnectAndRefreshAll
    devices = httpHandler.list_supported_devices()
  File "/var/www/html/plugins/meross/3rdparty/meross_iot/meross_iot/api.py", line 120, in list_supported_devices
    for dev in self.list_devices():
  File "/var/www/html/plugins/meross/3rdparty/meross_iot/meross_iot/api.py", line 114, in list_devices
    raise UnauthorizedException()
meross_iot.api.UnauthorizedException

## Contexte:
Lorsque le mot de passe du compte meross possède des caractères spéciaux, les commandes ne fonctionnent pas (sh meross.sh ... ou python3 meross.py....)

## Proposition de solution (optionnel):
* Dans le fichier /var/www/html/plugins/meross/core/class/merossCmd.class.php, ligne 32 
remplacer la ligne par celle ci-dessous
$command = 'sh ' . __DIR__ . '/../../3rdparty/meross.sh' . ' --email ' . $email . ' --password \'' . $password . '\' --uuid ' . $eqLogic->getLogicalId() . ' --show ';

* Dans le fichier /var/www/html/plugins/meross/core/class/meross.class.php, ligne 65 
remplacer par la ligne par celle ci-dessous
$command = "sh " . self::$_Script . ' --email ' . $email . ' --password \'' . $password . '\' ' . $_args;
## Environnement:

* **Version NextDom**:
* **Plateforme**: Debian Stretch
* **Version du Plugin**: develop

**Comment by slobberbone** [comment]
@mnpg tu ne veux pas proposer une PR ?
